version: "3.8"

services:
  traefik:
    image: traefik:v2.4
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      - VULTR_API_KEY=xxxxx
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=vultr
      - --certificatesresolvers.letsencrypt.acme.email=nick@maietta.org
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=letsencrypt
      
      - --entrypoints.websecure.http.tls.domains[0].main=maietta.org
      - --entrypoints.websecure.http.tls.domains[0].sans=*.maietta.org

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/letsencrypt

  website:
    image: nginx:latest
    volumes:
      - ./public_html:/usr/share/nginx/html
      # - ./nginx-default.conf:/etc/nginx/conf.d/default.conf

    restart: always
    labels:
      - "traefik.http.routers.website.rule=Host(`nick.maietta.org`)"

volumes:
  certs: